### ISSUE TITLE
Request: Ascent Guidance

### ISSUE THREAD

**Issue by solarisfire** [schlosrat/FlightPlan#13]
Firstly, AMAZING work so far, I really like the mod and it's working great with KSP2!

Can we get ascent guidance, please?? It's one of my favourite parts of Mechjeb2.

![image](https://github.com/schlosrat/FlightPlan/assets/420952/8a6c3746-f4a6-4176-a1f1-e5e09e19df52)

**Comment by schlosrat** [comment]
Thanks! I’m glad to hear you’re enjoying it!

Ascent guidance is one of my favorite parts of MJ too. If you want something similar right now then I suggest you check out either K2-D2 or KontrolSystem2, they both offer launch _and_ landing capabilities. K2-D2 also has Drone Mode for flying around while hovering, and KS2 is all about scripting things. Neither are quite as sophisticated as the MJ ascent guidance, but both are ready right out of the box!

Given how I’ve been integrating Flight Plan with K2-D2, I don’t really have plans to add that feature. I could probably get FP to call K2-D2 for a launch, but I think you’d be better off just using that mod directly for that part.

**Comment by solarisfire** [comment]
Yeah, I find the "lift" page very limited though... There are a lot of pieces missing that will become more important as the KSP2 devs enable things like heating! Ability to launch to rendezvous with another craft, etc.

**Comment by schlosrat** [comment]
I agree, and I do know that cfloutier is working on some improvements to that. For sure he plans to add staging and an option for auto deploy of solar panels. He and I have discussed launching into the target plane, and I've made the internal methods inside Flight Plan callable so that K2-D2 can access them. There's certainly hope for that, but I'd caution you that the MechJeb launch to rendezvous is a very very complex thing.

The last time I used MechJeb's Launch to Rendezvous it required that you first launch your rocket to a similar orbit, then revert to the pad and do it again. Without that first launch MJ had no good way of predicting *when* you'd get to the orbit, and so wouldn't be able to accurately time the launch so you'd arrive at a rendezvous. That's a *very* advanced capability.

As it happens, I just released FP 0.8.7 with a fairly good orbital rendezvous capability. If you don't mind packing along a little more fuel then you can easily use FP & K2-D2 to carry out a rendezvous that will put you within a few meters of your target. It's not so much like the MJ Rendezvous Autopilot (at least not yet), but more like the MJ Rendezvous Planner which guides your (or K2-D2's) steps.

**Comment by schlosrat** [comment]
FYI, if you'd like to join the conversation on Discord, you're welcome to. Here's where you can find us: https://discord.gg/eTyEWA74

**Comment by schlosrat** [comment]
@solarisfire, I'm going to repurpose this request to add support for better ascent guidance in K2-D2. There are definitely some things I can do on the FP side of the fence such as helping with launch into the plane of the target, etc. I'll make sure the support functions K2-D2 will need are present, but I'm going to leave it to K2-D2 to implement them rather than developing a whole new ascent capability that would just compete with what others are doing. When I get those capabilities made I'll close this issue.

**Comment by schlosrat** [comment]
I'm closing this issue as K2D2 is handling ascent guidance reasonably well, and any improvements are more likely to occur there. I will continue to work with that mod's developer for collaborative improvements in this and other areas. If you would like more or better autopilot features I encourage you to reach out to cfloutier on the [KSP2 Modding Society Discord] (https://discord.com/channels/1078696971088433153/1083306468540960768), or on his [GitHub repo] (https://github.com/cfloutier/k2d2), or on his [KSP2 Forum thread](https://forum.kerbalspaceprogram.com/topic/215664-k2-d2/)
