### ISSUE TITLE
UI Breaks when selecting a Body

### ISSUE THREAD

**Issue by kevin-huff** [schlosrat/FlightPlan#2]
![image](https://user-images.githubusercontent.com/56265219/234148632-d2c12a88-ba50-43c3-8c14-32a478029b0e.png)

First time using it selected Kerbin in the drop down for body and then all the text collapsed. persists after switching ships. Worked fine after saving and reloading from the main menu.

**Comment by schlosrat** [comment]
Can you tell me a little more so that i can try to recreate this?
Was you active vessel orbiting Kerbin at the time you selected it? If not, then what body were you orbiting?
Did you select Kerbin from the drop down menu, or were you using the in-game tools?
Any other info needed to reproduce the problem?

**Comment by schlosrat** [comment]
Bug confirmed. Fixed in version 0.7.4
